### ISSUE TITLE
edit ?edwSQL

### ISSUE THREAD

**Issue by thomaskhuang** [rparrish/RPamisc#12]
I have the RPamisc package working!  =)
Minor thing in the help file.  In the help example under 'Usage', the 'file' argument should have a value of FALSE, because it is a command string and not a file name, i.e.

edwSQL(sql = "SELECT TOP 10 * FROM Event_Cath", resource = "custom",
  custom = NULL, file = **FALSE**, DSN = FALSE, uid = NULL, pwd = NULL,
  ...)

**Comment by rparrish** [comment]
This is intentional. The reason why is because almost all the time, a .sql file will be used rather than including SQL in the function call.  Typical use  is: 
 `edwSQL("SQL/data_results.sql", resource = "EDWDBDev") `

Probably should split this into two different functions - one for straight SQL and another for working with SQL files. Need to think about this a bit more to avoid breaking existing R scripts.

**Comment by rparrish** [comment]
Decided to re-purpose the `edwQuery()` function to do the short SQL snippets. `edwSQL()` now only works with a separate .sql file.
